name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js | Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.QUICKJOBS_DATABASE_URL }}
        run: npm run drizzle:migrate

      - name: Check Migrations
        env:
          QUICKJOBS_DATABASE_URL: ${{ secrets.QUICKJOBS_DATABASE_URL }}
        run: npm run drizzle:check
